github-get-latest, allow other version

diff --git a/github-get-latest b/github-get-latest
--- a/github-get-latest
+++ b/github-get-latest
@@ -2,19 +2,45 @@
 
 # musl-cross-make-toybox/github-get-latest
 
-# take a github project url; download, unpack, and softlink the latest release
+set -eu
 
-set -euvx
+usage() {
+    cat <<EOF
+$(basename ${0}) GITHUB_URL [VERSION]
 
-export GITHUB_URL="${1}"
-export PROJECT="$(basename ${GITHUB_URL})"
+Download, unpack, and softlink a github project (latest release by default) in
+the current working directory.
+
+EOF
+}
+
+die() { { echo "ERROR: ${@}" ; usage ; } >&2 ; exit 1 ; }
+
+version_latest() {
+    (
+        cd $(mktemp -d)
+        curl -sL "${1}/releases" >releases
+        grep -Eo '[^/]+\.tar\.gz' releases >tarballs
+        sed 's/\.tar\.gz//' tarballs >versions
+        sort -Vo versions versions
+        tail -1 versions
+    )
+}
+
+if [ 1 -eq ${#} ]; then
+    github_url="${1}"
+    version="$(version_latest ${github_url})"
+elif [ 2 -eq ${#} ]; then
+    github_url="${1}"
+    version="${2}"
+else
+    die "bad args"
+fi
 cd $(mktemp -d)
-curl -sL ${GITHUB_URL}/releases \
-    | grep -Eo '[^/]+\.tar\.gz' | sed 's/\.tar\.gz//' | sort -V >versions
-export VERSION=$(tail -1 versions)
-curl -sLo ${PROJECT}_${VERSION}.tar.gz ${GITHUB_URL}/archive/${VERSION}.tar.gz
-tar -xf ${PROJECT}_${VERSION}.tar.gz
-untarred_dir=$(find $(pwd) -mindepth 1 -maxdepth 1 -type d)
+project="$(basename ${github_url})"
+curl -sLo ${project}_${version}.tar.gz ${github_url}/archive/${version}.tar.gz
+tar -xf ${project}_${version}.tar.gz
+untarred_dir=$(find ${PWD} -mindepth 1 -maxdepth 1 -type d)
 cd -
-mv -v ${untarred_dir} .
-ln -vs $(basename ${untarred_dir}) ${PROJECT}
+mv -v ${untarred_dir} ${PWD}
+ln -vs $(basename ${untarred_dir}) ${project}
